# Generated by Django 5.2.8 on 2025-11-16 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва резюме')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата оновлення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Резюме',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name="Повне ім'я")),
                ('job_title', models.CharField(max_length=100, verbose_name='Посада')),
                ('email', models.EmailField(max_length=254, verbose_name='Електронна адреса')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефону')),
                ('address', models.TextField(verbose_name='Адреса')),
                ('summary', models.TextField(verbose_name='Про себе')),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_info', to='resumes.resume', verbose_name='Резюме')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100, verbose_name='Компанія')),
                ('position', models.CharField(max_length=100, verbose_name='Посада')),
                ('start_date', models.DateField(verbose_name='Дата початку')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата закінчення')),
                ('currently_working', models.BooleanField(default=False, verbose_name='Працюю зараз')),
                ('description', models.TextField(verbose_name="Опис обов'язків")),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='resumes.resume', verbose_name='Резюме')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200, verbose_name='Навчальний заклад')),
                ('degree', models.CharField(max_length=100, verbose_name='Ступінь')),
                ('degree_type', models.CharField(choices=[('high_school', 'Середня школа'), ('bachelor', 'Бакалавр'), ('master', 'Магістр'), ('phd', 'Доктор наук'), ('certificate', 'Сертифікат'), ('other', 'Інше')], default='bachelor', max_length=20, verbose_name='Тип ступеня')),
                ('field_of_study', models.CharField(max_length=100, verbose_name='Спеціальність')),
                ('start_date', models.DateField(verbose_name='Дата початку')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата закінчення')),
                ('currently_studying', models.BooleanField(default=False, verbose_name='Навчаюсь зараз')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='resumes.resume', verbose_name='Резюме')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва навички')),
                ('level', models.CharField(choices=[('beginner', 'Початківець'), ('intermediate', 'Середній'), ('advanced', 'Просунутий'), ('expert', 'Експерт')], max_length=20, verbose_name='Рівень')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='Категорія')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='resumes.resume', verbose_name='Резюме')),
            ],
        ),
    ]
