# Generated by Django 5.2.8 on 2025-11-30 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва шаблону')),
                ('description', models.TextField(verbose_name='Опис')),
                ('template_type', models.CharField(choices=[('modern', 'Сучасний'), ('classic', 'Класичний'), ('creative', 'Креативний'), ('minimal', 'Мінімалістичний')], default='modern', max_length=20, verbose_name='Тип шаблону')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='template_previews/', verbose_name='Зображення перегляду')),
                ('html_template', models.TextField(verbose_name='HTML шаблон')),
                ('css_styles', models.TextField(verbose_name='CSS стилі')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Преміум')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Ціна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Шаблон резюме',
                'verbose_name_plural': 'Шаблони резюме',
            },
        ),
        migrations.AlterField(
            model_name='resume',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата створення'),
        ),
        migrations.AddField(
            model_name='resume',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resumes.resumetemplate', verbose_name='Шаблон'),
        ),
    ]
