# Generated by Django 5.2.8 on 2025-12-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_resumetemplate_alter_resume_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Фото'),
        ),
    ]
