# Generated by Django 5.2.8 on 2025-12-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_personalinfo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='photo',
            field=models.ImageField(blank=True, help_text='Завантажте ваше фото для резюме', null=True, upload_to='resume_photos/', verbose_name='Фотографія'),
        ),
    ]
